Group9_iCareApp/Controllers/DisplayMyBoardController.cs
using Group9_iCareApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace Group9_iCareApp.Controllers
{
    public class DisplayMyBoardController : Controller
    {
        private readonly iCAREDBContext _context;
        UserManager<iCAREUser> _userManager;

        public DisplayMyBoardController(iCAREDBContext context, UserManager<iCAREUser> userManager)
        {
            _context = context; // grabs the database context and the usermanager
            _userManager = userManager;
        }

        //Sorts the list of patients based on the sortOrder to be viewed in the view.
        public IActionResult Index(string sortOrder)
        {
            ViewData["NameSortParm"] = sortOrder == "name_asc" ? "name_desc" : "name_asc";
            ViewData["BirthDateSortParm"] = sortOrder == "birthdate_asc" ? "birthdate_desc" : "birthdate_asc";

            // Track current sort column and direction
            ViewData["CurrentSortColumn"] = sortOrder?.Split('_')[0] ?? "name"; //Default to name if null
            ViewData["CurrentSortDirection"] = sortOrder?.Split('_')[1] ?? "desc"; // Default to ascending if null

            string userID = _userManager.GetUserId(User) ?? string.Empty;
            if (!userID.IsNullOrEmpty()) // user exists
            {
                iCAREWorker worker = _context.iCAREWorkers.FirstOrDefault(w => w.UserAccount == userID); // grabs the worker of the current user
                var patients = _context.PatientRecords.Where(c => c.TreatmentRecords.Any(i => i.WorkerId == worker.Id)).AsQueryable(); //grabs all patients assigned to worker

                patients = sortOrder switch
                {
                    "name_desc" => patients.OrderByDescending(d => d.Fname),
                    "name_asc" => patients.OrderBy(d => d.Fname),
                    "birthdate_desc" => patients.OrderByDescending(d => d.DateOfBirth),
                    "birthdate_asc" => patients.OrderBy(d => d.DateOfBirth),
                    _ => patients.OrderByDescending(d => d.Fname) // Default sort by firstname descending
                };
                ViewData["patients"] = patients.ToList();
            }
            return View();
        }

        //Shows the details of a specific patient based on their id.
        public IActionResult Details(int patientId)
        {
            var patient = _context.PatientRecords.Find(patientId);
            if (patient == null)
            {
                TempData["ErrorMessage"] = "Patient cannot be found.";
            }
            return View(patient);
        }

        //Given the patient(based on Id), manage the patient's information to change if needed.
        public IActionResult ManagePatient(int patientId)
        {
            DbSet<PatientRecord> allRecords = _context.PatientRecords;
            PatientRecord patient = allRecords.Find(patientId);  // Find the requested patient
            ViewData["bloodtypes"] = iCAREBoardController.bloodGroups;
            return View(patient);
        }

        //Given the patient, update it within the database and go back to myBoard.
        [HttpPost]
        public ActionResult Edit(PatientRecord patient)
        {
            DbSet<PatientRecord> allRecords = _context.PatientRecords; // gets all patientrecords
            allRecords.Update(patient); // updates patient record values
            _context.SaveChanges(); // saves changes to database
            TempData["SuccessMessage"] = "Successfully modified " + patient.Fname + " " + patient.Lname + "'s information.";
            return RedirectToAction("Index"); // redirects back to view of all patients
        }

        // Initializes given data for a new treatment record, but then sends to the view to get the rest to treat a patient.
        public IActionResult TreatPatient(int patientId)
        {
            ViewData["Drugs"] = new SelectList(_context.DrugsDictionaries, "Id", "Name");
            string userID = _userManager.GetUserId(User) ?? string.Empty;
            if (!userID.IsNullOrEmpty())
            {
                iCAREWorker worker = _context.iCAREWorkers.FirstOrDefault(w => w.UserAccount == userID); // gets current worker from userid
                if (worker != null) // if worker exists
                {
                    ViewData["WorkerId"] = worker.Id; //if this fails, the view will know about it
                }
            }
            // Initialize the model with today's date for TreatmentDate
            var treatmentRecord = new TreatmentRecord
            {
                TreatmentId = Guid.NewGuid().ToString(),
                TreatmentDate = DateTime.Now,
                PatientId = patientId,
            };
            return View(treatmentRecord);
        }

        //Having created a new treatmentRecord, checks if valid and saves to database. Success = details of patient, showing new record.
        // Failure = go back to treatPatient view.
        [HttpPost]
        public IActionResult CreateTreatmentRecord(TreatmentRecord treatmentRecord)
        {
            if (ModelState.IsValid)
            {
                _context.TreatmentRecords.Add(treatmentRecord);
                _context.SaveChanges(); // adds treatment record to patientrecord and saves changes to the database
                return RedirectToAction("Details", new { patientId = treatmentRecord.PatientId });
            }
            ViewData["ErrorMessage"] = "Sorry, treating a patient failed! If this occurs again, contact help!"; //shouldn't ever occur.
            return RedirectToAction("TreatPatient", new { patientId = treatmentRecord.PatientId });
        }
    }
}

Group9_iCareApp/Controllers/ManageDocumentController.cs
using Group9_iCareApp.Models;
using Microsoft.AspNetCore.Mvc;
using Aspose.Words;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace Group9_iCareApp.Controllers
{
    public class ManageDocumentController : Controller
    {

        private readonly iCAREDBContext db = new();
        private readonly UserManager<iCAREUser> userManager;
        //not allowing all extensions to just be uploaded. Covers basic images, docs, and pdfs.
        private readonly string[] permittedExtensions = { ".png", ".jpg", ".jpeg", ".doc", ".docx", ".pdf" };

        //injects userManager to allow for checking what User is currently here.
        public ManageDocumentController(UserManager<iCAREUser> userManager)
        {
            this.userManager = userManager;
        }
        //makes sure that if someone goes to /ManageDocument/ URL, it redirects it to Palette.
        public IActionResult Index()
        {
            return RedirectToAction("Palette");
        }

        //if someone tries to access /ManageDocument/ManageDocument directly, just redirect them to creating a new document.
        public IActionResult ManageDocument()
        {
            return RedirectToAction("CreateDocument"); 
        }

        //The Palette shows documents that have to do with the patients assigned to the worker. Based on the given inputs, it can sort and filter the documents by patient.
        //The default is by names in alphabetical order.
        [HttpGet]
        public async Task<IActionResult> Palette(string? sortOrder, int? patientId)
        {
            ViewData["NameSortParm"] = sortOrder == "name_asc" ? "name_desc" : "name_asc"; 
            ViewData["LastModifiedSortParm"] = sortOrder == "modified_asc" ? "modified_desc" : "modified_asc";
            ViewData["CreationSortParm"] = sortOrder == "creation_asc" ? "creation_desc" : "creation_asc"; 
            //If it was already sorted by some caegory x ascending or descending, then the next time it is sorted again, is it the other way around.
            //If there was no order, the default is ascending for when the button pressed.

            // Track current sort column and direction
            ViewData["CurrentSortColumn"] = sortOrder?.Split('_')[0] ?? "name"; //Default to name if null
            ViewData["CurrentSortDirection"] = sortOrder?.Split('_')[1] ?? "desc"; // Default to ascending if null
            ViewData["patients"] = await CreatePatientSelectList();

            // Set sort and filter parameters
            ViewData["currentSortOrder"] = sortOrder;
            ViewData["currentPatientId"] = patientId;

            // Fetch documents
            var documents = db.Documents.AsQueryable();
            if (patientId.HasValue) //if we are filtering by a patient.
            {
                 documents = documents.Where(d => d.PatientRecordId == patientId);
            }
            else
            {
                //other wise just get all documents associated with this patient.
                var assignedPatientIds = await FindAssignedPatientIds();
                documents = documents.Where(d => assignedPatientIds.Contains(d.PatientRecordId));
            }
            
            //sorts depending on the sortOrder chosen.
            documents = sortOrder switch
            {
                "name_desc" => documents.OrderByDescending(d => d.DocumentName),
                "name_asc" => documents.OrderBy(d => d.DocumentName),
                "modified_desc" => documents.OrderByDescending(d => d.LastModifiedDate),
                "modified_asc" => documents.OrderBy(d => d.LastModifiedDate),
                "creation_desc" => documents.OrderByDescending(d => d.CreationDate),
                "creation_asc" => documents.OrderBy(d => d.CreationDate),
                _ => documents.OrderByDescending(d => d.DocumentName) // Default sort by DocumentName descending
            };
            
            //pass the list of documents to be viewed.
            return View(await documents.ToListAsync());
        }

        //Creates a new document, sets up necessary information such as the treatments to select one, and whether this is a new document(important for the view).
        public async Task<IActionResult> CreateDocument()
        {
            ViewData["Document"] = new Group9_iCareApp.Models.Document();
            ViewData["htmlString"] = string.Empty; //empty for new document//
            ViewData["editOldDoc"] = false;
            ViewData["treatments"] = await CreateTreatmentSelectList();
            ViewData["drugs"] = db.DrugsDictionaries.ToList();
            return View("ManageDocument");
        }

        //Editing a document is stil the same view, but finds the original information associated with the document so that it is available to be edited. Requires a fileName to do.
        public async Task<IActionResult> EditDocument(string fileName)
        {
            var document = db.Documents.Find(fileName);
            if (document == null)
            {
                return RedirectToAction("CreateDocument"); //can't find document, so just attempts to make new one instead.
            }
            var htmlString = ConvertPdfToHtml(document.Data);
            ViewData["Document"] = document;
            ViewData["htmlString"] = htmlString;
            ViewData["editOldDoc"] = true;
            ViewData["treatments"] = await CreateTreatmentSelectList();
            ViewData["drugs"] = db.DrugsDictionaries.ToList();
            return View("ManageDocument");
        }

        //Views a document given the fileName. Shows associated metadata in it.
        public IActionResult ViewDocument(string fileName)
        {

            var document = db.Documents.Find(fileName);
            if (document != null)
            {   
                //attempts to find the names of the Creator/Last Modifier to be displayed to the view.
                var creatingWorker = db.iCAREWorkers.Find(document.CreatingWorkerId);
                if(creatingWorker != null)
                {
                    var creatingUser = db.iCAREUsers.Find(creatingWorker.UserAccount);
                    if(creatingUser != null)
                    {
                        ViewData["CreatorName"] = creatingUser.Fname + " " + creatingUser.Lname;
                    }
                }

                var modifyingWorker = db.iCAREWorkers.Find(document.ModifyingWorkerId);
                if (modifyingWorker != null)
                {
                    var modifyingUser = db.iCAREUsers.Find(modifyingWorker.UserAccount);
                    if (modifyingUser != null)
                    {
                        ViewData["ModifierName"] = modifyingUser.Fname + " " + modifyingUser.Lname;
                    }
                }
            }

            return View(document);
        }

        //returns the data associated with the document to be viewed as a PDF for the worker.
        public IActionResult ViewPdf(string fileName)
        {
            var document = db.Documents.Find(fileName);
            return File(document.Data, "application/pdf");
        }

        //Deletes a document given its name. It redirects to Palette to show that the document is not available to view anymore.
        public IActionResult DeleteDocument(string fileName)
        {
            var doc = db.Documents.Find(fileName);
            if (doc != null && ModelState.IsValid)
            {
                db.Documents.Remove(doc);
                db.SaveChanges();
            }
            return RedirectToAction("Palette");
        }

        //Given the content(the htmlstring), the docName, a proto document with some relevant information, and the description, ensures that the document is created and successfully put into the database.
        [HttpPost]
        public IActionResult SaveNewDocument(string content, string DocumentName, Group9_iCareApp.Models.Document protoDoc, string Description)
        {
            if (string.IsNullOrEmpty(content) || string.IsNullOrEmpty(DocumentName) || db.Documents.Find(DocumentName + ".pdf") != null) 
            {
                //nothing in doc, nothing in docName, or doc already exists.
                return NoContent();
            }

            // Convert HTML content to PDF
            Aspose.Words.Document doc = new();
            var builder = new DocumentBuilder(doc);
            builder.InsertHtml(content);
            using MemoryStream outStream = new();
            doc.Save(outStream, SaveFormat.Pdf);
            byte[] bytes = outStream.ToArray();

            var treatment = db.TreatmentRecords.FirstOrDefault(p => p.TreatmentId == protoDoc.treatmentID);

            int workerID = FindCurrentWorkerId();
            Group9_iCareApp.Models.Document document = new()
            {
                DocumentName = DocumentName + ".pdf",
                Data = bytes,
                CreationDate = DateTime.Now,
                CreatingWorkerId = workerID,
                PatientRecordId = treatment.PatientId,
                LastModifiedDate = DateTime.Now,
                ModifyingWorkerId = workerID,
                Description = Description,
                treatmentID = treatment.TreatmentId
            };


            db.Documents.Add(document);
            db.SaveChanges();

            return RedirectToAction("Palette"); //go back to Viewing the list of docs to see update.
        }

        //Given the new content, the docName, and the new(possibly) description, updates the document in the database.
        [HttpPost]
        public IActionResult SaveOldDocument(string content, string docName, string Description)
        {
            if (string.IsNullOrEmpty(content) || string.IsNullOrEmpty(docName)) 
            {
                //nothing in doc or nothing in docName.
                return NoContent();
            }

Group9_iCareApp/Views/ManageDocument/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Handle Documents";
}


<div class="text-center">
    <h1 class="display-4">FileUpload</h1>
</div>

<div class="container">
    <div class="mb-3 mt-3">
        <form asp-controller="ManageDocument" asp-action="UploadFile" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label class="form-label">Upload File</label>
                <input type="file" name="file" class="form-control" />
            </div>
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Upload</button>
            </div>
        </form>
     </div>
</div>

Group9_iCareApp/Views/ManageDocument/ManageDocument.cshtml
@model Group9_iCareApp.Models.Document
@{
    Document document = (Document)ViewData["Document"];
    string htmlString = (string)ViewData["htmlString"];
    bool editOldDoc = (bool)ViewData["editOldDoc"];
    var treatments = (SelectList)ViewData["treatments"];
    var drugs = (List<DrugsDictionary>)ViewData["drugs"];
}

@if (treatments == null || !treatments.Any())
{
    <p>Currently, you have no patients assigned to you, so you can't create any documents. Feel free to assign yourself some patients!</p>
}
else
{
    <div class="text-center">
        <h1 class="display-4">@((editOldDoc ? "Edit Document" : "Create Document") + ": " + document.DocumentName)</h1>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@(editOldDoc ? "Edit Document" : "Create Document")</title>
        <link rel="stylesheet" href="../../assets/vendor/ckeditor5/ckeditor5.css">
        <style>
            .main-container {
                width: 795px;
                margin-left: auto;
                margin-right: auto;
            }
        </style>
    </head>
    <body>
        <form asp-controller="ManageDocument" asp-action="@(editOldDoc ? "SaveOldDocument" : "SaveNewDocument")" method="post">
            
            <div class="main-container">
                <div class="form-group">
                    <label asp-for="Description">Description </label>
                    <input asp-for="Description" class="form-control" maxlength="20" placeholder="Enter a brief description" value="@document.Description" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <br />
                <!-- Display document name input if in create mode -->
                @if (!editOldDoc)
                {
                    <div class="form-group">
                        <br />
                        <label asp-for="DocumentName">Document Name</label>
                        <input asp-for="DocumentName" class="form-control" maxlength="20" placeholder="Enter document name here" />
                        <span asp-validation-for="DocumentName" class="text-danger"></span>
                        <label class="mt-4" for="treatmentId">Treatments</label>
                        <select asp-for="treatmentID" asp-items=treatments class="form-select"></select>
                    </div>
                }
                else
                {
                    <input type="hidden" name="docName" value="@document.DocumentName" />
                }

                <!-- Editor with HTML content or empty for new documents -->
                <br />
                <div class="editor-container editor-container_classic-editor" id="editor-container">
                    <div class="editor-container__editor">
                        <textarea name="content" id="editor">
                            @Html.Raw(htmlString)
                        </textarea>
                    </div>
                    <p><input type="submit" value="Submit to Database" class="btn btn-primary"></p>
                </div>
            </div>
            <!-- Hidden field to pass the editOldDoc flag to the controller -->
            <input type="hidden" name="editOldDoc" value="@editOldDoc" />
        </form>

        <script type="importmap">
            {
                "imports": {
                    "ckeditor5": "../../assets/vendor/ckeditor5/ckeditor5.js",
                    "ckeditor5/": "../../assets/vendor/ckeditor5/",
                    "ckeditor5-premium-features": "../../assets/vendor/ckeditor5-premium-features/ckeditor5-premium-features.js",
                    "ckeditor5-premium-features/": "../../assets/vendor/ckeditor5-premium-features/"
                }
            }
        </script>
        <script type="module" src="../../assets/vendor/main.js"></script>
    </body>
    </html>
    <!-- Display the drugs table -->
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Shortcut</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var drug in drugs)
            {
                <tr>
                    <td>@drug.Name</td>
                    <td>@drug.Name.Substring(0, 3).ToLowerInvariant()</td>
                    <td>@drug.Description</td>
                </tr>
            }
        </tbody>
    </table>
}

Group9_iCareApp/Views/ManageDocument/Palette.cshtml
@model IEnumerable<Group9_iCareApp.Models.Document>
@{
    var patients = (SelectList)ViewData["patients"];
}

<a asp-controller="ManageDocument" asp-action="CreateDocument" class="btn btn-primary">Create New Document</a>
<a asp-controller="ManageDocument" asp-action="UploadDocument" class="btn btn-secondary">Upload Documents</a>
<br />

@if (patients == null || !patients.Any())
{
        <p>Currently, you have no patients assigned to you. Feel free to assign yourself some patients!</p>

}
else if (!Model.Any())
{
        <p>Currently, no documents for your patients exist. Feel free to upload or create a document for them!</p>
}
else
{
        <form asp-action="Palette" asp-route-sortOrder=@ViewData["currentSortOrder"] method="get">
            <div class="form-group">
                <label for="patientId">Filter by Patient</label>
                <select name="patientId" class="form-control" id="patientId">
                    <option value="">All Patients</option> <!-- Default option to show all patients -->
                @foreach (var patient in patients)
                {
                    @if (patient.Value.ToString().Equals(ViewData["currentPatientId"]?.ToString()))
                    {
                                    <option value="@patient.Value" selected>@patient.Text</option>
                    }
                    else
                    {
                                    <option value="@patient.Value">@patient.Text</option>
                    }

                }
                </select>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Filter</button>
            </div>
        </form>
        <table class="table">
            <tr>
                <th>
                    <a asp-action="Palette" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-patientId="@ViewData["currentPatientId"]" >
                    @Html.DisplayNameFor(model => model.DocumentName)
                    @if ((string)ViewData["CurrentSortColumn"] == "name")
                    {
                                <span>@((string)ViewData["CurrentSortDirection"] == "asc" ? "▲" : "▼")</span>
                    }

                    </a>
                </th>
                <th>
                    <a asp-action="Palette" asp-route-sortOrder="@ViewData["LastModifiedSortParm"]" asp-route-patientId="@ViewData["currentPatientId"]">
                    @Html.DisplayNameFor(model => model.LastModifiedDate)
                    @if ((string)ViewData["CurrentSortColumn"] == "modified")
                    {
                                <span>@((string)ViewData["CurrentSortDirection"] == "asc" ? "▲" : "▼")</span>
                    }

                    </a>
                </th>
                <th>
                    <a asp-action="Palette" asp-route-sortOrder="@ViewData["CreationSortParm"]" asp-route-patientId="@ViewData["currentPatientId"]">
                    @Html.DisplayNameFor(model => model.CreationDate)
                    @if ((string)ViewData["CurrentSortColumn"] == "creation")
                    {
                                <span>@((string)ViewData["CurrentSortDirection"] == "asc" ? "▲" : "▼")</span>
                    }

                    </a>
                </th>
                <th>
                @Html.DisplayNameFor(model => model.Description)
                </th>
            </tr>

        @foreach (var item in Model)
        {
                    <tr>
                        <td>
                    @Html.DisplayFor(modelItem => item.DocumentName)
                        </td>
                        <td>
                    @Html.DisplayFor(modelItem => item.LastModifiedDate)
                        </td>
                        <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                        </td>
                        <td>
                    @Html.DisplayFor(modelItem => item.Description)
                        </td>


                        <td>
                    @Html.ActionLink("View", "ViewDocument", "ManageDocument", new { fileName = item.DocumentName })
                        </td>
                        <td>
                    @Html.ActionLink("Edit", "EditDocument", "ManageDocument", new { fileName = item.DocumentName })
                        </td>
                        <td>
                    @Html.ActionLink("Delete", "DeleteDocument", "ManageDocument", new { fileName = item.DocumentName })
                        </td>
                    </tr>
        }
        </table>
}

Group9_iCareApp/Views/ManageDocument/UploadDocument.cshtml
@model Group9_iCareApp.Models.Document
@{
    string error = (string)TempData["ErrorMessage"];
    string success = (string)TempData["SuccessMessage"];
    var treatments = (SelectList)ViewData["treatments"];
}


@if (treatments == null || !treatments.Any())
{
    <p>Currently, you have no patients assigned to you, so you can't upload any documents. Feel free to assign yourself some patients!</p>
}
else
{
    <div class="text-center">
        <h1 class="display-4">Document Upload</h1>
    </div>


    <p>Only PNGs, JPEGs, Microsoft Word documents, and PDFs will be accepted to be uploaded. </p>

    <div class="container">
        <div class="mb-3 mt-3">
            <form asp-controller="ManageDocument" asp-action="UploadFile" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="Description">Description</label>
                    <input type="text" name="Description" class="form-control" id="Description" placeholder="Enter a brief description" />
                </div>
                <br />
                <div class="form-group">
                    <label class="mt-4" for="treatmentID">Treatment</label>
                    <select asp-for="treatmentID" asp-items=treatments class="form-select"></select>
                </div>

                <div class="mb-3">
                    <input type="file" name="file" class="form-control" />
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Upload</button>
                    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>

    @if (@error != null)
    {
        <div class="alert alert-danger" role="alert">
            @error
        </div>
    }

    @if (@success != null)
    {
        <div class="alert alert-success" role="alert">
            @success
        </div>
    }
}

Group9_iCareApp/Views/ManageDocument/ViewDocument.cshtml
@model Group9_iCareApp.Models.Document
@inject iCAREDBContext db
@{
    PatientRecord patient = db.PatientRecords.Find(Model.PatientRecordId);
    string? creatorName = (string?)ViewData["CreatorName"];
    string? lastModifierName = (string?)ViewData["ModifierName"];
}

@if (Model != null){
    <h1>@Model.DocumentName</h1>
    <a asp-controller="ManageDocument" asp-action="EditDocument" asp-route-fileName="@Model.DocumentName" class="btn btn-primary">Edit Document</a>
    <object data='@Url.Action("ViewPdf", "ManageDocument", new {fileName = Model.DocumentName})' width="100%" height="600px" name=@Model.DocumentName></object>
    
    <div>
        <h1>Document Details</h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            Description
        </dt>
        <dd class="col-sm-9">
            @Model.Description
        </dd>
        <dt class="col-sm-3">
            Patient 
        </dt>
        <dd class="col-sm-9">
            @patient.Fname @patient.Lname
        </dd>

        <dt class="col-sm-3">
            Creation Date
        </dt>
        <dd class="col-sm-9">
            @Model.CreationDate
        </dd>
            @if(creatorName != null)
            {
                <dt class="col-sm-3">
                    Created by
                </dt>
                <dd class="col-sm-9">
                    @creatorName
                </dd>
            }    
        <dt class="col-sm-3">
            Last Modified Date
        </dt>
        <dd class="col-sm-9">
            @Model.LastModifiedDate
        </dd>
            @if(lastModifierName != null)
            {
                <dt class="col-sm-3">
                    Last Modified by
                </dt>
                <dd class="col-sm-9">
                    @lastModifierName
                </dd>
            }    
    </dl>
</div>
    <a asp-controller="DisplayMyBoard" asp-action="Details" asp-route-patientId="@Model.PatientRecordId" class="btn btn-primary">View Associated Patient</a>
}
else
{
    <h3>Sorry!</h3>
    <p>The document you are trying to view cannot be found.</p>
}